In [1]:
mylist=[1,2,3]

In [2]:
mylist

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3])

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
  np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.30981405, 0.98594015, 0.19858631, 0.04286756, 0.13936357])

In [16]:
np.random.randn(2,3)

array([[-0.40002129, -1.44147698,  0.33193363],
       [ 0.02981978,  0.9917391 , -1.53432417]])

In [17]:
np.random.randint(0,100,10)

array([85, 81,  4, 38, 85, 95, 85, 48, 94, 28])

In [18]:
arr=np.arange(25)

In [19]:
ranarr=np.random.randint(0,50,10)

In [20]:
arr=arr.reshape(5,5)

In [21]:
ranarr

array([ 1, 15, 22, 31, 22,  5, 45, 45,  7, 37])

In [22]:
ranarr.max()

45

In [23]:
ranarr.argmax()

6

# return index of max value (argmax) and min value(argmin)

In [24]:
ranarr.argmin()

0

In [25]:
arr.shape

(5, 5)

In [26]:
arr.dtype

dtype('int32')

In [27]:
ranarr.dtype

dtype('int32')

In [28]:
arr=np.arange(0,10)

In [29]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[8]

8

In [31]:
newarr=np.arange(0,10)

In [32]:
newarr.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
newarr.shape

(10,)

In [34]:
np.random.randint(0,10,4).reshape((2,2))

array([[7, 2],
       [6, 4]])

In [35]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [36]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
arr[0:5]=100

In [38]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [39]:
arr=np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
slice_of_arr=arr[0:6]

In [42]:
slice_of_arr[:]=99

In [43]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [44]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [45]:
copy_arr=arr.copy()

In [46]:
copy_arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
copy_arr[0:4]=100

In [48]:
copy_arr

array([100, 100, 100, 100,  99,  99,   6,   7,   8,   9,  10])

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [51]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [53]:
bigarr=np.arange(0,25).reshape(5,5)

In [54]:
bigarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
bigarr[2:,2:]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [56]:
arr=np.arange(1,11)

In [57]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [59]:
 arr<5
    

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [60]:
bool_arr=arr>5

In [61]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [62]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [63]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [64]:
arr[arr<=3]

array([1, 2, 3])

In [65]:
bigarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
bigarr>2

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [71]:
arr=np.arange(0,9).reshape((3,3))

In [77]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# NumPy Operations
Array with Array\
Array with Scalars\
Universal Array Function

In [80]:
arr=np.arange(0,11)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [88]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [90]:
arr/arr

C:\Users\varun\AppData\Local\Temp\ipykernel_14360\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [91]:
1/arr

C:\Users\varun\AppData\Local\Temp\ipykernel_14360\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [92]:
arr**2


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [93]:
arr.argsort()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [104]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [94]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [96]:
np.max(arr)

10

In [97]:
np.min(arr)

0

In [98]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [99]:
np.log(arr)

C:\Users\varun\AppData\Local\Temp\ipykernel_14360\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
arr.argmin()

0